name: release
on:
  push:
    branches:
      - main
jobs:
  releaser:
    runs-on: [self-hosted, linux]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Remove old output if exists
        run: |
          rm -rf output-debian-minimal-* 
      - name: Packer Build
        run: |
          echo "Validating Image Files.."
          packer build --on-error=ask -force --var-file="debian-builder.json" --var-file="debian-version-11.6.0.json" debian-minimal.json
